Repository oduck-team/oduck-server, pull requests merged in 2023-08, with the labels that each got.

#10 프로젝트 추가 세팅(http header 보안, logger, docker)
  .dockerignore
  .env.example
  README.md
  dockerfile
  docs/docker.md
  docs/env.md
  docs/nestjs.md
  docs/prisma.md
  nestia.config.ts
  package-lock.json
  package.json
  src/app.module.ts
  src/domain/user/users.controller.ts
  src/domain/user/users.module.ts
  src/global/config/swagger/index.ts
  src/global/config/winston/index.ts
  src/global/utils/controllerPathfinder.util.ts
  src/main.ts
Labels: setting

#5 prisma를 이용한 모델 스키마 작성
  prisma/schema.prisma
Labels: feature

#14 한줄 리뷰, 장문 리뷰 api 추가
  dist/swagger.json
  prisma/schema.prisma
  src/app.module.ts
  src/domain/review/controller/long-review.controller.ts
  src/domain/review/controller/short-review.controller.ts
  src/domain/review/dto/review-request.dto.ts
  src/domain/review/dto/review-response.dto.ts
  src/domain/review/repository/long-review.repository.ts
  src/domain/review/repository/short-review.repository.ts
  src/domain/review/reviews.interface.ts
  src/domain/review/reviews.module.ts
  src/domain/review/service/long-review.service.ts
  src/domain/review/service/short-review.service.ts
  src/global/config/prisma/prisma.module.ts
  src/global/config/prisma/prisma.service.ts
  test/unit/review/long-review.repository.spec.ts
  test/unit/review/long-review.service.spec.ts
  test/unit/review/short-review.repository.spec.ts
  test/unit/review/short-review.service.spec.ts
Labels: feature, refactor

#13 Auth 및 Member 기능 추가
  .env.example
  .gitignore
  dist/swagger.json
  docker-compose.yml
  docs/docker.md
  nestia.config.ts
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.module.ts
  src/domain/member/dto/RequestMember.dto.ts
  src/domain/member/dto/ResponseMember.dto.ts
  src/domain/member/interface/member.interface.ts
  src/domain/member/member.controller.ts
  src/domain/member/member.module.ts
  src/domain/member/member.repository.ts
  src/domain/member/member.service.ts
  src/domain/user/dto/create-user.dto.ts
  src/domain/user/users.controller.ts
  src/domain/user/users.module.ts
  src/global/auth/auth.controller.ts
  src/global/auth/auth.module.ts
  src/global/auth/auth.service.ts
  src/global/auth/guard/google.auth.guard.ts
  src/global/auth/guard/kakao.auth.guard.ts
  src/global/auth/guard/naver.auth.guard.ts
  src/global/auth/guard/roles.guard.ts
  src/global/auth/serializer.ts
  src/global/auth/strategy/google.strategy.ts
  src/global/auth/strategy/kakao.strategy.ts
  src/global/auth/strategy/naver.starategy.ts
  src/global/common/decoratror/roles.decorator.ts
  src/global/common/decoratror/user.decorator.ts
  src/global/libs/redis.ts
  src/main.ts
Labels: docs, feature, refactor, setting

#19 긴급: memberRepository di 및 예외 처리, README.md 수정
  README.md
  dist/swagger.json
  prisma/schema.prisma
  src/domain/member/member.controller.ts
  src/domain/member/member.module.ts
  src/domain/member/member.repository.ts
  src/domain/member/member.service.ts
  src/global/auth/auth.controller.ts
Labels: refactor, emergency

#28 긴급! 프론트로 쿠키세션 전달 안 되던 문제 해결 및 세션ID 변경 #27
  dist/swagger.json
  nestia.config.ts
  src/global/auth/auth.controller.ts
  src/main.ts
Labels: refactor, emergency

#26 API 응답, 글로벌 예외 필터 추가
  src/app.module.ts
  src/domain/review/repository/long-review.repository.ts
  src/domain/review/repository/short-review.repository.ts
  src/domain/review/reviews.module.ts
  src/global/common/filter/http-exception.filter.ts
  src/global/common/filter/prisma-exception.filter.ts
  src/global/common/response/api-response.ts
  src/global/config/prisma/prisma.module.ts
  src/global/config/prisma/prisma.service.ts
  src/global/database/prisma/prisma.module.ts
  src/global/database/prisma/prisma.service.ts
  tests/unit/review/long-review.repository.spec.ts
  tests/unit/review/long-review.service.spec.ts
  tests/unit/review/short-review.repository.spec.ts
  tests/unit/review/short-review.service.spec.ts
Labels: feature, setting, test
