Repository oduck-team/oduck-server, pull requests merged in 2023-09, with the labels that each got.

#31 회원 도메인 추가 #20
  dist/swagger.json
  package.json
  prisma/schema.prisma
  src/app.module.ts
  src/domain/member/dto/RequestMember.dto.ts
  src/domain/member/dto/ResponseMember.dto.ts
  src/domain/member/interface/member.interface.ts
  src/domain/member/member.controller.ts
  src/domain/member/member.module.ts
  src/domain/member/member.repository.ts
  src/domain/member/member.service.ts
  src/global/auth/auth.controller.ts
  src/main.ts
  tests/unit/member/member.repository.spec.ts
  tests/unit/member/member.service.spec.ts
Labels: docs, feature, refactor, test

#34 리뷰 좋아요 기능 추가 및 개선
  dist/swagger.json
  prisma/schema.prisma
  src/domain/review/controller/long-review.controller.ts
  src/domain/review/controller/short-review.controller.ts
  src/domain/review/dto/review-request.dto.ts
  src/domain/review/dto/review-response.dto.ts
  src/domain/review/repository/long-review.repository.ts
  src/domain/review/repository/short-review.repository.ts
  src/domain/review/reviews.interface.ts
  src/domain/review/service/short-review.service.ts
  src/global/common/filter/http-exception.filter.ts
  src/global/common/filter/prisma-exception.filter.ts
  tests/unit/review/short-review.repository.spec.ts
  tests/unit/review/short-review.service.spec.ts
Labels: feature, refactor

#33 북마크(입덕하기) 기능을 구현한다 #32
  dist/swagger.json
  prisma/schema.prisma
  src/app.module.ts
  src/domain/bookmark/bookmark.controller.ts
  src/domain/bookmark/bookmark.module.ts
  src/domain/bookmark/bookmark.repository.ts
  src/domain/bookmark/bookmark.service.ts
  src/domain/bookmark/dto/bookmark.req.dto.ts
  src/domain/bookmark/dto/bookmark.res.dto.ts
  src/domain/member/dto/member.req.dto.ts
  src/domain/member/dto/member.res.dto.ts
  src/domain/member/member.controller.ts
  src/domain/member/member.module.ts
  tests/unit/bookmark/bookmark.repository.spec.ts
  tests/unit/bookmark/bookmark.service.spec.ts
Labels: docs, feature, refactor

#38 로컬 회원가입 및 관리자 로그인
  dist/swagger.json
  package-lock.json
  package.json
  prisma/schema.prisma
  src/domain/bookmark/dto/bookmark.res.dto.ts
  src/domain/member/dto/member.req.dto.ts
  src/domain/member/dto/member.res.dto.ts
  src/domain/member/interface/member.interface.ts
  src/domain/member/member.controller.ts
  src/domain/member/member.repository.ts
  src/domain/member/member.service.ts
  src/global/auth/auth.controller.ts
  src/global/auth/auth.module.ts
  src/global/auth/auth.service.ts
  src/global/auth/guard/admin.auth.guard.ts
  src/global/auth/guard/local.auth.guard.ts
  src/global/auth/session.serializer.ts
  src/global/auth/strategy/admin.strategy.ts
  src/global/auth/strategy/google.strategy.ts
  src/global/auth/strategy/kakao.strategy.ts
  src/global/auth/strategy/local.strategy.ts
  src/global/auth/strategy/naver.starategy.ts
  src/global/utils/bcrypt.ts
Labels: feature, refactor

#42 긴급) 회원 생성 DTO 적용 안 했던 걸 수정 #41
  dist/swagger.json
  src/domain/member/dto/member.req.dto.ts
  src/domain/member/member.controller.ts
Labels: refactor

#44 긴급) 회원 로그인, 관리자 로그인 api 분리 -> 서비스 분리
  dist/swagger.json
  docker-compose.yml
  src/global/auth/auth.controller.ts
  src/global/auth/auth.module.ts
  src/global/auth/auth.service.ts
  src/global/auth/guard/admin.auth.guard.ts
  src/global/auth/strategy/admin.strategy.ts
Labels: feature
