Repository oduck-team/oduck-server, pull requests merged in 2023-12, with the labels that each got.

#134 짧은 리뷰 작성 수정 및 인가 추가 #117
  src/main/java/io/oduck/api/domain/review/controller/ShortReviewController.java
  src/main/java/io/oduck/api/domain/review/dto/ShortReviewReqDto.java
  src/main/java/io/oduck/api/global/security/config/SecurityConfig.java
  src/test/java/io/oduck/api/e2e/shortReview/ShortReviewControllerTest.java
  src/test/java/io/oduck/api/global/utils/ShortReviewTestUtils.java
Labels: Feature, Refactor

#131 작성한 리뷰 목록에 애니 제목 추가 #130
  src/main/java/io/oduck/api/domain/member/controller/MemberController.java
  src/main/java/io/oduck/api/domain/member/dto/MemberDslDto.java
  src/main/java/io/oduck/api/domain/review/dto/ShortReviewDslDto.java
  src/main/java/io/oduck/api/domain/review/dto/ShortReviewReqDto.java
  src/main/java/io/oduck/api/domain/review/dto/ShortReviewResDto.java
  src/main/java/io/oduck/api/domain/review/repository/ShortReviewRepositoryCustom.java
  src/main/java/io/oduck/api/domain/review/repository/ShortReviewRepositoryImpl.java
  src/main/java/io/oduck/api/domain/review/service/ShortReviewService.java
  src/main/java/io/oduck/api/domain/review/service/ShortReviewServiceImpl.java
  src/main/java/io/oduck/api/global/config/WebConfig.java
  src/main/java/io/oduck/api/global/converter/StringToMemerReviewsConverter.java
Labels: Refactor

#137 짧은 리뷰 좋아요shortReviewId DTO로 요청 전달 #132
  src/main/java/io/oduck/api/domain/review/dto/ShortReviewResDto.java
  src/main/java/io/oduck/api/domain/reviewLike/controller/ShortReviewLikeController.java
  src/main/java/io/oduck/api/domain/reviewLike/service/ShortReviewLikeService.java
  src/main/java/io/oduck/api/domain/reviewLike/service/ShortReviewLikeServiceImpl.java
  src/test/java/io/oduck/api/e2e/shortReview/ShortReviewControllerTest.java
  src/test/java/io/oduck/api/e2e/shortReviewLike/ShortReviewLikeControllerTest.java
  src/test/java/io/oduck/api/unit/shortReviewLike/service/ShortReviewLikeServiceTest.java
Labels: Feature, Test

#144 주간 인기 애니 조회 #140
  src/main/java/io/oduck/api/domain/anime/controller/AnimeController.java
  src/main/java/io/oduck/api/domain/anime/entity/Anime.java
  src/main/java/io/oduck/api/domain/anime/service/AnimeServiceImpl.java
  src/main/java/io/oduck/api/domain/genre/repository/GenreRepositoryCustom.java
  src/main/java/io/oduck/api/domain/genre/repository/GenreRepositoryCustomImpl.java
  src/main/java/io/oduck/api/domain/review/dto/ShortReviewResDto.java
  src/main/java/io/oduck/api/domain/review/repository/ShortReviewRepositoryImpl.java
  src/main/java/io/oduck/api/domain/review/service/ShortReviewServiceImpl.java
  src/main/java/io/oduck/api/domain/weekly/dto/WeeklyDsl.java
  src/main/java/io/oduck/api/domain/weekly/dto/WeeklyRes.java
  src/main/java/io/oduck/api/domain/weekly/entity/WeeklyAnime.java
  src/main/java/io/oduck/api/domain/weekly/repository/WeeklyAnimeRepository.java
  src/main/java/io/oduck/api/domain/weekly/repository/WeeklyAnimeRepositoryCustom.java
  src/main/java/io/oduck/api/domain/weekly/repository/WeeklyAnimeRepositoryCustomImpl.java
  src/main/java/io/oduck/api/domain/weekly/service/WeeklyAnimeService.java
  src/main/java/io/oduck/api/domain/weekly/service/WeeklyAnimeServiceImpl.java
  src/main/java/io/oduck/api/global/scheduler/weekly/WeeklyAnimeScheduled.java
  src/main/java/io/oduck/api/global/utils/QueryDslUtils.java
Labels: Feature, Refactor

#148 주간 인기 애니 조회 쿼리 수정 #147
  src/main/java/io/oduck/api/domain/genre/repository/GenreRepositoryCustomImpl.java
Labels: Refactor

#155 짧은 리뷰 좋아요 유무 uri변경 #152
  src/main/java/io/oduck/api/domain/reviewLike/controller/ShortReviewLikeController.java
  src/main/java/io/oduck/api/domain/reviewLike/service/ShortReviewLikeService.java
  src/main/java/io/oduck/api/domain/reviewLike/service/ShortReviewLikeServiceImpl.java
  src/main/java/io/oduck/api/global/security/config/SecurityConfig.java
  src/test/java/io/oduck/api/e2e/shortReviewLike/ShortReviewLikeControllerTest.java
  src/test/java/io/oduck/api/unit/shortReviewLike/service/ShortReviewLikeServiceTest.java
Labels: Refactor, Setting, Test

#149 입덕포인트 평균 수정 및 회원, 애니 id 로 입덕포인트 수정 #145
  src/main/java/io/oduck/api/domain/attractionPoint/controller/AttractionPointController.java
  src/main/java/io/oduck/api/domain/attractionPoint/dto/AttractionPointReqDto.java
  src/main/java/io/oduck/api/domain/attractionPoint/dto/AttractionPointResDto.java
  src/main/java/io/oduck/api/domain/attractionPoint/repository/AttractionPointRepositoryCustom.java
  src/main/java/io/oduck/api/domain/attractionPoint/repository/AttractionPointRepositoryImpl.java
  src/main/java/io/oduck/api/domain/attractionPoint/service/AttractionPointService.java
  src/main/java/io/oduck/api/domain/attractionPoint/service/AttractionPointServiceImpl.java
  src/test/java/io/oduck/api/e2e/attractionPoint/AttractionPointControllerTest.java
  src/test/java/io/oduck/api/unit/attractionPoint/service/AttractionPointServiceTest.java
Labels: Bug fix, Docs, Feature, Refactor, Test
